[Feature] Add "/conversations/join" endpoint
wireapp/wire-ios-mocktransport pull request #174
Opened 2021-06-11 16:27 UTC by KaterinaWire

## What's new in this PR?

There's a new `/conversations/join` endpoint and a response for it.

2021-06-14 06:09 UTC, typfel requested changes

2021-06-14 06:09 UTC, typfel commented on Source/Users/MockUser.swift
> +    public static func insertUserWith(name: String, in context: NSManagedObjectContext) -> MockUser {
The there's already a method on the `MockTransportSession` for inserting a user https://github.com/wireapp/wire-ios-mocktransport/blob/c7fcf86b07b18c610c384dd63dd857154c34ab36/Source/MockTransportSession.m#L629

2021-06-14 06:09 UTC, typfel commented on Source/Conversations/MockTransportSession+conversations.swift
> +    public func processJoinConversation(with payload: [String: AnyHashable]) -> ZMTransportResponse {
So this mock now always creates a new conversation when you call `/conversation/join`, you came to the conclusion that this behaviour is enough to write the integration tests you need?

2021-06-14 18:00 UTC, KaterinaWire commented on Source/Users/MockUser.swift
> +    public static func insertUserWith(name: String, in context: NSManagedObjectContext) -> MockUser {
Yes, you are right, but this method wasn't available from the swift code. I converted it to Swift and removed the objc version.

2021-06-14 18:07 UTC, KaterinaWire commented on Source/Conversations/MockTransportSession+conversations.swift
> +    public func processJoinConversation(with payload: [String: AnyHashable]) -> ZMTransportResponse {
Yes. I cover 2 cases:
- success
- 404: "no-conversation-code".

There's one more error 403: "too-many-members", but I don't know how can I cover it here.

And also there's a `204` response (the user was already part of that conversation), that I would like to cover in SE. Btw, we aren't going to change the `204` response, instead of that we should trigger another request to get the conversation ID.

2021-06-15 06:31 UTC, johnxnguyen commented on Source/Conversations/MockTransportSession+conversations.m
> +    else if ([request matchesWithPath:@"/conversations/join" method:ZMMethodPOST]) {
This is going to change to a GET endpoint, right?

2021-06-15 22:23 UTC, KaterinaWire commented on Source/Conversations/MockTransportSession+conversations.m
> +    else if ([request matchesWithPath:@"/conversations/join" method:ZMMethodPOST]) {
No, this's a mock response for the `POST` method. I also added a new request `GET conversation/join`

2021-06-16 06:40 UTC, johnxnguyen commented on Source/Conversations/MockTransportSession+conversations.m
> +        return [self processFetchConversationWithPayload:[request.payload asDictionary]];
I thought this endpoint uses query parameters instead of a payload?

2021-06-18 11:04 UTC, johnxnguyen reviewed
Do we need to add tests?

2021-06-18 11:04 UTC, johnxnguyen commented on Source/Conversations/MockTransportSession+conversations.swift
> +                "name" : "Test"] as ZMTransportData
I think this whole method implementation would be more readable by using a switch:

```swift
guard let code = query["code"] as? String else { ... }

switch code {
case "existing-conversation-code":
  let payload = ...
  return ZMTransportResponse(payload: ...)

case "test-code":
  let payload = ...
  return ZMTransportResponse(payload: ...)

default:
  let payload = ...
  return ZMTransportResponse(payload: ...)  
}
```

2021-06-18 12:52 UTC, KaterinaWire commented on Source/Conversations/MockTransportSession+conversations.m
> +        return [self processFetchConversationWithPayload:[request.payload asDictionary]];
Changed

2021-06-18 15:17 UTC, KaterinaWire commented on Source/Conversations/MockTransportSession+conversations.swift
> +        /// - "wrong-code" - there should be an error in the response payload
Done

2021-06-18 15:18 UTC, KaterinaWire commented on Source/Conversations/MockTransportSession+conversations.swift
> +                "name" : "Test"] as ZMTransportData
Done

2021-06-18 15:39 UTC, typfel approved these changes

2021-06-21 05:33 UTC, KaterinaWire commented
> Do we need to add tests?

Added tests

2021-06-21 06:45 UTC, johnxnguyen approved these changes

2021-06-21 08:15 UTC, merged